# Generated by Django 4.2.3 on 2023-08-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name="article",
            name="redacted_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(("published_at__lte", models.F("redacted_at"))),
                name="check_published_redacted_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="article",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("published_at__isnull", False),
                    models.Q(("published_at__isnull", True), ("redacted_at__isnull", True)),
                    _connector="OR",
                ),
                name="check_published_if_redacted",
            ),
        ),
    ]
