version: "3.9"
services:
  backoffice:
    build: .
    ports:
      - "8000:8000"
      - "9091:9091"
    command: poetry run backoffice-start
    volumes:
      - .:/src
    environment:
      - "DJANGO_SETTINGS_MODULE=localdev.settings"
      - "DJANGO_CONFIGURATION=Backoffice"
      - "CORE_DATABASE_NAME=postgres"
      - "CORE_DATABASE_HOST=db"
      - "CORE_DATABASE_USER=postgres"
      - "CORE_DATABASE_PASSWORD=postgres"
      - "CORE_DATABASE_PORT=5432"
      - "LOCALDEV=true"
    depends_on:
      - db

  api:
    build: .
    ports:
      - "8001:8001"
    command: poetry run api-start
    volumes:
      - .:/src
    environment:
      - "DJANGO_SETTINGS_MODULE=localdev.settings"
      - "DJANGO_CONFIGURATION=Backoffice"
      - "CORE_DATABASE_NAME=postgres"
      - "CORE_DATABASE_HOST=db"
      - "CORE_DATABASE_USER=postgres"
      - "CORE_DATABASE_PASSWORD=postgres"
      - "CORE_DATABASE_PORT=5432"
      - "LOCALDEV=true"
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgresdata:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

volumes:
  postgresdata:
