"""
Django settings for backoffice project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from typing import Any

from configurations import Configuration

from queenbees.utils import environ


class Base(Configuration):
    # Other sites URLs
    BACKOFFICE_URL = environ.get_str("BACKOFFICE_URL")
    API_URL = environ.get_str("API_URL")

    # Build paths inside the project like this: BASE_DIR / 'subdir'.
    BASE_DIR = Path(__file__).resolve().parent.parent.parent
    INTERFACE_DIR = BASE_DIR.joinpath("queenbees", "interfaces")
    DOTENV = os.path.join(BASE_DIR, ".env")

    # Quick-start development settings - unsuitable for production
    # See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

    # SECURITY WARNING: keep the secret key used in production secret!
    SECRET_KEY = environ.get_str("DJANGO_SECRET_KEY")

    # SECURITY WARNING: don't run with debug turned on in production!
    DEBUG = True

    ALLOWED_HOSTS: list[str] = []
    REDIRECT_TO_LOGIN = False

    # Application definition

    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "queenbees.core.content",
        "health_check",
        "health_check.db",
    ]

    MIDDLEWARE = [
        "django.middleware.security.SecurityMiddleware",
        "django.contrib.sessions.middleware.SessionMiddleware",
        "django.middleware.common.CommonMiddleware",
        "django.middleware.csrf.CsrfViewMiddleware",
        "django.contrib.auth.middleware.AuthenticationMiddleware",
        "django.contrib.messages.middleware.MessageMiddleware",
        "django.middleware.clickjacking.XFrameOptionsMiddleware",
    ]

    ROOT_URLCONF = "queenbees.core.interfaces.urls"

    HEALTH_CHECK: dict[str, Any] = {
        "DISK_USAGE_MIN": 90,
        "MEMORY_MIN": 100,
        "SUBSETS": {
            "startup-probe": ["MigrationHealthCheck", "DatabaseBackend"],
            "liveliness-probe": ["DatabaseBackend"],
        },
    }

    # Template settings
    TEMPLATE_DIRS = [INTERFACE_DIR.joinpath("common", "templates")]
    TEMPLATES = [
        {
            "BACKEND": "django.template.backends.django.DjangoTemplates",
            "DIRS": TEMPLATE_DIRS,
            "APP_DIRS": True,
            "OPTIONS": {
                "context_processors": [
                    "django.template.context_processors.debug",
                    "django.template.context_processors.request",
                    "django.contrib.auth.context_processors.auth",
                    "django.contrib.messages.context_processors.messages",
                ],
            },
        },
    ]

    WSGI_APPLICATION = "wsgi.application"

    # Database
    # https://docs.djangoproject.com/en/4.2/ref/settings/#databases

    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": environ.get_str("CORE_DATABASE_NAME"),
            "USER": environ.get_str("CORE_DATABASE_USER"),
            "PASSWORD": environ.get_str("CORE_DATABASE_PASSWORD"),
            "HOST": environ.get_str("CORE_DATABASE_HOST"),
            "PORT": environ.get_int("CORE_DATABASE_PORT"),
            "TEST": {
                "NAME": "tests_core",
            },
        }
    }
    PYTEST_SETUP_DATABASES = [
        "default",
    ]
    IGNORE_OPERATION_SETTINGS = False

    # Password validation
    # https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]

    # Internationalization
    # https://docs.djangoproject.com/en/4.2/topics/i18n/

    LANGUAGE_CODE = "en-us"

    TIME_ZONE = environ.get_str("TIMEZONE", "UTC")

    USE_I18N = True

    USE_TZ = True

    # Static files (CSS, JavaScript, Images)
    # https://docs.djangoproject.com/en/4.2/howto/static-files/

    STATIC_URL = "static/"

    STATICFILES_DIRS: list[Path] = []

    # Default primary key field type
    # https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

    DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

    # Content management
    BROKEN_MEDIA_URL = ""
    DRAFT_EXPIRY_DAYS: int = 30

    # APIs
    GRAPHENE: dict[str, str] = {
        "SCHEMA": "queenbees.interfaces.api.graphql.schema",
    }
