name: "Auto approval"
run-name: "auto-approval"

on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  approve-owner:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.user.login == github.repository_owner }}
    steps:
      - name: Approve changes
        run: gh pr review $PR_URL --approve -b "Approving changes made by repository owner."
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
