name: "Clear auto-merge"
run-name: "clear-auto-merge"

on: pull_request

permissions:
  pull-requests: write
  contents: write

jobs:
  clear-auto-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Disable auto-merge
        run: gh pr merge --disable-auto --merge "$PR_URL" || true
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
