name: "js-tests"
run-name: "js-tests"
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: "ubuntu-latest"
    container: "python:3.11-bookworm"
    services:
      postgres:
        image: "postgres:15"
        ports:
          - 5432/tcp
        env:
          POSTGRES_PASSWORD: "postgres"
        # Ensure Postgres is available
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DJANGO_CONFIGURATION: "Base"
      DJANGO_SETTINGS_MODULE: "queenbees.settings"
      CORE_DATABASE_NAME: "postgres"
      CORE_DATABASE_HOST: "postgres"
      CORE_DATABASE_USER: "postgres"
      CORE_DATABASE_PASSWORD: "postgres"
      CORE_DATABASE_PORT: "5432"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: touch src/.env

      - name: Install npm
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        uses: eslint/github-action@v0

      - name: Run JS tests
        run: npm test
